version: '3'

services:
  frontend:
    build: ./packages/frontend
    ports:
      - "3000:3000"
  backend:
    build: ./packages/backend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"