version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: nevlemar_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME:-nevlemar}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-nevlemar2026}
    ports:
      - "27017:27017"
    volumes:
      - nevlemar_mongo_data:/data/db

volumes:
  nevlemar_mongo_data:
