version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./packages/backend
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_USERNAME: root
      DB_PASSWORD: example
    depends_on:
      - mongodb
    ports:
      - "3001:3001"

  frontend:
    build: ./packages/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
